CREATE DATABASE IF NOT EXISTS db_usuarios;
CREATE DATABASE IF NOT EXISTS db_estaciones;
CREATE DATABASE IF NOT EXISTS db_reservas;
CREATE DATABASE IF NOT EXISTS db_sesiones;
CREATE DATABASE IF NOT EXISTS db_membresias;
CREATE DATABASE IF NOT EXISTS db_pagos;
CREATE DATABASE IF NOT EXISTS db_espera;
CREATE DATABASE IF NOT EXISTS db_notificaciones;
CREATE DATABASE IF NOT EXISTS db_reportes;
CREATE DATABASE IF NOT EXISTS db_promociones;

GRANT ALL PRIVILEGES ON *.* TO 'adminapp'@'%';
FLUSH PRIVILEGES;