spring.application.name=api-gateway

server.port=8080

# EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# GATEWAY DISCOVERY
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# RUTA HACIA MICROSERVICIO USUARIO
spring.cloud.gateway.routes[0].id=usuario-service
spring.cloud.gateway.routes[0].uri=lb://USUARIO
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/usuarios/**